### ISSUE TITLE
 Could this library be used with the MAX11300PMB1 board? 

### ISSUE THREAD

**Issue by JnsVttr** [wolfgangfriedrich/Pixi_demo#1]
the MAX11300 seems to be really amazing - can the library also be used with the MAX11300PMB1 board, or only with the MAX11300 Arduino shield?  

https://www.maximintegrated.com/en/products/analog/data-converters/analog-to-digital-converters/MAX11300PMB1.html

**Comment by wolfgangfriedrich** [comment]
It should work if the SPI interface is wired correctly to the Arduino board of choice. SCLKL, MISO and MISO are dedicated pins. CS, is basically a GPIOs, currently mapped to pin 10 on the Arduino shield. If you use a different pin (especially if you are not using an Uno) the Pixi.cpp file needs to be edited to account for the different pin.

`// set pin 10 as the slave select for the SPI interface:
const int slaveSelectPin = 10;
`

The INTB and CNVTB signals are not implemented at all in my library

As you can see, the code is quite old and after glancing through, it looks like I have only implemented the DAC and ADC feature. 

What I do remember is, that the MAX11300 requires a negative voltage at Vavssio to be able to output a 0V level. So setting the jumper Vssio on the MAX11300PMB1 board to GND is not ideal. 

![image](https://user-images.githubusercontent.com/13815559/67535980-5f497180-f6ab-11e9-9ef8-e4684094cde8.png)

**Comment by JnsVttr** [comment]
thank you! I successfully tested the MAX11300PMB1 now with Teensy 3.2 and apparently in the library the SPI clock speed needs to be adapted to 20MHz:

`SPI.begin();` 
`// SPI.setClockDivider(SPI_CLOCK_DIV2);` 
`// SPI.setDataMode(SPI_MODE0);` 
`// SPI.setBitOrder(MSBFIRST) ; ` 
`SPI.beginTransaction(SPISettings(20000000, MSBFIRST, SPI_MODE0));` 

and thanks so much for this library!

**Comment by wolfgangfriedrich** [comment]
Thanks for the feedback and I am glad this lib works for you.

Viel Erfolg mit deinem Projekt.

**Comment by tanvir-kishan** [comment]
Can I used this library without the analog shield. I have a MAX11300 PMB1 that is connected to the Arduino with SPI connection?

**Comment by wolfgangfriedrich** [comment]
Hello tanvir-kishan,
Other people asked the same question and were able to successfully use the library with the PMB1 board and you are welcome to use it too.. You might need to configure the SPCI clock speed. good luck with your project.  - W.

**Comment by tanvir-kishan** [comment]
> thank you! I successfully tested the MAX11300PMB1 now with Teensy 3.2 and apparently in the library the SPI clock speed needs to be adapted to 20MHz:
> 
> `SPI.begin();` `// SPI.setClockDivider(SPI_CLOCK_DIV2);` `// SPI.setDataMode(SPI_MODE0);` `// SPI.setBitOrder(MSBFIRST) ; ` `SPI.beginTransaction(SPISettings(20000000, MSBFIRST, SPI_MODE0));`
> 
> and thanks so much for this library!



Hi, I am trying to use the max11300pmb1 as ADC with Arduino. Do you have a sample code that I can look into? Thanks in advance
